// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7tXd4OqpbldG85z40JzVc4SmDxadG394',
    appId: '1:965677707311:web:6986dadd2547e4ace1d6da',
    messagingSenderId: '965677707311',
    projectId: 'final-3c764',
    authDomain: 'final-3c764.firebaseapp.com',
    storageBucket: 'final-3c764.firebasestorage.app',
    measurementId: 'G-HK4M7VDGYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbFxjamv_qDIr_I7l9-NExO6aaukhmAK4',
    appId: '1:965677707311:android:91bbdce2a78268b4e1d6da',
    messagingSenderId: '965677707311',
    projectId: 'final-3c764',
    storageBucket: 'final-3c764.firebasestorage.app',
  );
}
